Remove before logging, log removals

diff --git a/snippets/s3_diff_docker_import.erb b/snippets/s3_diff_docker_import.erb
--- a/snippets/s3_diff_docker_import.erb
+++ b/snippets/s3_diff_docker_import.erb
@@ -38,7 +38,7 @@ remove_bad_imports() {
   log "removing bad imports"
   images=$(docker images | grep \<none | awk '{ print $3 }')
   if [[ "x$images" != "x" ]]; then
-    docker rmi $images
+    docker rmi $images > >(log)
   fi
   log "bad import removed"
 }
@@ -54,8 +54,7 @@ log "fetch: successfully pulled base image"
 worked=1
 for attempt in {1..200}; do
   [[ $worked != 0 ]] || break
-  stream_image | docker_import && worked=0 || (log "fetch: attempt $attempt failed, sleeping 30"; sleep 30)
-  [[ $worked != 0 ]] && remove_bad_imports
+  stream_image | docker_import && worked=0 || (remove_bad_imports; log "fetch: attempt $attempt failed, sleeping 30"; sleep 30)
 done
 [[ $worked != 0 ]] && fatal "fetch: failed to import diff image"
 log "fetch: successfully imported diff image"
